version: "3.9"
   
services:
  ayopop-proxy:
    build: ./source/ayopop-proxy/
  graphql:
    build: ./source/graphql/
    ports:
      - "18000:8000"
    depends_on:
      - ayopop-proxy

